#ifndef SDEVICESR830_GLOBAL_H
#define SDEVICESR830_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SDEVICESR830_LIB
# define SDEVICESR830_EXPORT Q_DECL_EXPORT
#else
# define SDEVICESR830_EXPORT Q_DECL_IMPORT
#endif

#endif // SDEVICESR830_GLOBAL_H
