#ifndef SDEVICEAPSIN20G_GLOBAL_H
#define SDEVICEAPSIN20G_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SDEVICEAPSIN20G_LIB
# define SDEVICEAPSIN20G_EXPORT Q_DECL_EXPORT
#else
# define SDEVICEAPSIN20G_EXPORT Q_DECL_IMPORT
#endif

#endif // SDEVICEK2400_GLOBAL_H
