#ifndef SDEVICEPSAE4440A_GLOBAL_H
#define SDEVICEPSAE4440A_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SDEVICEPSAE4440A_LIB
# define SDEVICEPSAE4440A_EXPORT Q_DECL_EXPORT
#else
# define SDEVICEPSAE4440A_EXPORT Q_DECL_IMPORT
#endif

#endif // SDEVICEPSAE4440A_GLOBAL_H
