#ifndef SPINTOOLBOXSDK_H
#define SPINTOOLBOXSDK_H

#define STB_SDK
#define STB_SDK_MAJOR_VERSION 1
#define STB_SDK_MINOR_VERSION 3
#define STB_SDK_VERSION SDK_MAJOR_VERSION.SDK_MINOR_VERSION



#endif