#ifndef SDEVICEPSGE8257D_GLOBAL_H
#define SDEVICEPSGE8257D_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SDEVICEPSGE8257D_LIB
# define SDEVICEPSGE8257D_EXPORT Q_DECL_EXPORT
#else
# define SDEVICEPSGE8257D_EXPORT Q_DECL_IMPORT
#endif

#endif // SDEVICEPSGE8257D_GLOBAL_H
