#ifndef SDEVICERSSMA100A_GLOBAL_H
#define SDEVICERSSMA100A_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SDEVICERSSMA100A_LIB
# define SDEVICERSSMA100A_EXPORT Q_DECL_EXPORT
#else
# define SDEVICERSSMA100A_EXPORT Q_DECL_IMPORT
#endif

#endif // SDEVICERSSMA100A_GLOBAL_H
