#ifndef SDEVICEDAQFIELDONEAXIS_GLOBAL_H
#define SDEVICEDAQFIELDONEAXIS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SDEVICEDAQFIELDONEAXIS_LIB
# define SDEVICEDAQFIELDONEAXIS_EXPORT Q_DECL_EXPORT
#else
# define SDEVICEDAQFIELDONEAXIS_EXPORT Q_DECL_IMPORT
#endif

#endif // SDEVICEDAQFIELDONEAXIS_GLOBAL_H
