#ifndef STEXTFILESPLITTERPLUGIN_GLOBAL_H
#define STEXTFILESPLITTERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef STEXTFILESPLITTERPLUGIN_LIB
# define STEXTFILESPLITTERPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define STEXTFILESPLITTERPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // STEXTFILESPLITTERPLUGIN_GLOBAL_H
